package com.dubbo.demo.model;

import java.io.Serializable;

public class TDepartment implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.depa_id
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    private Integer depaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.depa_name
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    private String depaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.depa_no
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    private Integer depaNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.is_del
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.depa_status
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    private Integer depaStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.depa_id
     *
     * @return the value of t_department.depa_id
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    public Integer getDepaId() {
        return depaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.depa_id
     *
     * @param depaId the value for t_department.depa_id
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    public void setDepaId(Integer depaId) {
        this.depaId = depaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.depa_name
     *
     * @return the value of t_department.depa_name
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    public String getDepaName() {
        return depaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.depa_name
     *
     * @param depaName the value for t_department.depa_name
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    public void setDepaName(String depaName) {
        this.depaName = depaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.depa_no
     *
     * @return the value of t_department.depa_no
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    public Integer getDepaNo() {
        return depaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.depa_no
     *
     * @param depaNo the value for t_department.depa_no
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    public void setDepaNo(Integer depaNo) {
        this.depaNo = depaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.is_del
     *
     * @return the value of t_department.is_del
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.is_del
     *
     * @param isDel the value for t_department.is_del
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.depa_status
     *
     * @return the value of t_department.depa_status
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    public Integer getDepaStatus() {
        return depaStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.depa_status
     *
     * @param depaStatus the value for t_department.depa_status
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    public void setDepaStatus(Integer depaStatus) {
        this.depaStatus = depaStatus;
    }
}