package com.dubbo.demo.mapper;

import com.dubbo.demo.model.TDepartment;
import com.dubbo.demo.model.TDepartmentExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    long countByExample(TDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    int deleteByExample(TDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    int deleteByPrimaryKey(Integer depaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    int insert(TDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    int insertSelective(TDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    List<TDepartment> selectByExample(TDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    TDepartment selectByPrimaryKey(Integer depaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") TDepartment record, @Param("example") TDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    int updateByExample(@Param("record") TDepartment record, @Param("example") TDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    int updateByPrimaryKeySelective(TDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbg.generated Sat Apr 07 16:53:15 CST 2018
     */
    int updateByPrimaryKey(TDepartment record);
    
    List<TDepartment> findDepartmentList(@Param("param") Map<String, Object> param);
}